sudo: required

services:
  - docker

before_install:
  - docker build -t jacklaurenson/react-test -f client/Dockerfile.dev client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t jacklaurenson/multi-client ./client
  - docker build -t jacklaurenson/multi-nginx ./nginx
  - docker build -t jacklaurenson/multi-server ./server
  - docker build -t jacklaurenson/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push jacklaurenson/multi-client
  - docker push jacklaurenson/multi-nginx
  - docker push jacklaurenson/multi-server
  - docker push jacklaurenson/multi-worker
